module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Colors from Landing Page Design
        'surface-container-highest': '#26364a',
        'tertiary': '#e9c349',
        'surface-bright': '#2a3a4f',
        'on-error-container': '#ffdad6',
        'primary': '#94d3c1',
        'on-tertiary-fixed-variant': '#574500',
        'surface-tint': '#94d3c1',
        'surface-container-lowest': '#000f21',
        'on-secondary-container': '#adb4ce',
        'surface-container-high': '#1b2b3f',
        'inverse-primary': '#29695b',
        'secondary-container': '#3f465c',
        'outline': '#89938f',
        'error': '#ffb4ab',
        'surface': '#031427',
        'surface-variant': '#26364a',
        'tertiary-container': '#cca730',
        'on-surface': '#d3e4fe',
        'surface-container': '#102034',
        'outline-variant': '#3f4945',
        'on-primary-fixed': '#00201a',
        'tertiary-fixed-dim': '#e9c349',
        'surface-dim': '#031427',
        'on-primary-container': '#7ebdac',
        'secondary-fixed': '#dae2fd',
        'on-background': '#d3e4fe',
        'inverse-on-surface': '#213145',
        'inverse-surface': '#d3e4fe',
        'on-tertiary': '#3c2f00',
        'on-primary-fixed-variant': '#065043',
        'primary-container': '#004d40',
        'on-secondary-fixed-variant': '#3f465c',
        'on-error': '#690005',
        'primary-fixed-dim': '#94d3c1',
        'on-tertiary-fixed': '#241a00',
        'on-secondary-fixed': '#131b2e',
        'background': '#031427',
        'on-secondary': '#283044',
        'error-container': '#93000a',
        'surface-container-low': '#0b1c30',
        'secondary': '#bec6e0',
        'tertiary-fixed': '#ffe088',
        'on-primary': '#00382e',
        'secondary-fixed-dim': '#bec6e0',
        'on-surface-variant': '#bfc9c4',
        'primary-fixed': '#afefdd',
        'on-tertiary-container': '#4f3e00',
        'on-primary-fixed': '#00201a',
        'primary': '#94d3c1',
        'on-primary-fixed': '#00201a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        xl: '48px',
        md: '16px',
        sm: '8px',
        lg: '24px',
        'container-max': '1440px',
        'gutter': '20px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Archivo Narrow'],
        'headline-lg': ['Archivo Narrow'],
        'display-lg': ['Archivo Narrow'],
        'title-md': ['Geist'],
        'data-tabular': ['JetBrains Mono'],
        'label-sm': ['Geist'],
        'body-md': ['Geist'],
        sans: ['Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'data-tabular': ['13px', { lineHeight: '16px', fontWeight: '450' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('tailwindcss/plugin')(function ({ addUtilities }) {
      addUtilities({
        '.scrollbar-hide': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
      });
    }),
  ],
}
