import type {
  FollowedItem,
  FanMatch,
  FanFeedItem,
  FanLeaderboardUser,
  FanStats,
} from '../types'

export const INITIAL_FOLLOWED_ITEMS: FollowedItem[] = [
  {
    id: 'club-petro',
    type: 'club',
    name: 'Petro Atlético de Luanda',
    slug: 'petro-atletico',
    badgeUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=150&auto=format&fit=crop&q=80',
    subtitle: 'Girabola · 1º Lugar',
    category: 'Sénior & Formação',
    followedAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'club-primeiro-agosto',
    type: 'club',
    name: '1º de Agosto',
    slug: '1-de-agosto',
    badgeUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=150&auto=format&fit=crop&q=80',
    subtitle: 'Girabola · 2º Lugar',
    category: 'Sénior & Academia',
    followedAt: '2026-09-05T14:30:00Z',
  },
  {
    id: 'player-zito-lubece',
    type: 'player',
    name: 'Zito Luvumbo',
    slug: 'zito-luvumbo',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    subtitle: 'Extremo Direito · 23 anos',
    category: 'Petro de Luanda',
    followedAt: '2026-09-10T11:20:00Z',
  },
  {
    id: 'player-gilberto-mabululu',
    type: 'player',
    name: 'Gilberto "Gibelé"',
    slug: 'gilberto-gibele',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    subtitle: 'Médio Ofensivo · 21 anos',
    category: 'Academia Sambizanga',
    followedAt: '2026-09-12T09:15:00Z',
  },
  {
    id: 'comp-girabola',
    type: 'competition',
    name: 'Girabola 2026/27',
    slug: 'girabola-26-27',
    badgeUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=150&auto=format&fit=crop&q=80',
    subtitle: '1ª Divisão Nacional',
    followedAt: '2026-08-20T08:00:00Z',
  },
]

export const MOCK_UPCOMING_MATCHES: FanMatch[] = [
  {
    id: 'match-derby-luanda-01',
    competitionId: 'girabola',
    competitionName: 'Girabola — Jornada 14',
    round: 'Grande Dérbi de Luanda',
    date: '2026-10-03',
    time: '16:30',
    venue: 'Estádio 11 de Novembro',
    city: 'Luanda',
    status: 'scheduled',
    hasFollowedTeam: true,
    homeTeam: {
      id: 'club-petro',
      name: 'Petro de Luanda',
      shortName: 'PET',
      logoUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=120&auto=format&fit=crop&q=80',
    },
    awayTeam: {
      id: 'club-primeiro-agosto',
      name: '1º de Agosto',
      shortName: 'PRI',
      logoUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=120&auto=format&fit=crop&q=80',
    },
  },
  {
    id: 'match-u19-taça-02',
    competitionId: 'taca-juniores',
    competitionName: 'Taça Provincial Sub-19',
    round: 'Quartos de Final',
    date: '2026-10-04',
    time: '10:00',
    venue: 'Campo do São Paulo',
    city: 'Luanda',
    status: 'scheduled',
    hasFollowedTeam: true,
    homeTeam: {
      id: 'club-sambizanga',
      name: 'Academia Sambizanga',
      shortName: 'SAM',
    },
    awayTeam: {
      id: 'club-interclube',
      name: 'Interclube Sub-19',
      shortName: 'INT',
    },
  },
  {
    id: 'match-sagrada-williette-03',
    competitionId: 'girabola',
    competitionName: 'Girabola — Jornada 14',
    round: 'Fase Regular',
    date: '2026-10-04',
    time: '15:00',
    venue: 'Estádio Sagrada Esperança',
    city: 'Dundo',
    status: 'scheduled',
    hasFollowedTeam: false,
    homeTeam: {
      id: 'club-sagrada',
      name: 'Sagrada Esperança',
      shortName: 'SAG',
    },
    awayTeam: {
      id: 'club-williete',
      name: 'Wiliete SC',
      shortName: 'WIL',
    },
  },
]

export const MOCK_FEED_ITEMS: FanFeedItem[] = [
  {
    id: 'feed-01',
    type: 'highlight',
    title: 'Golaço de fora da área no treino de preparação',
    summary: 'Gilberto "Gibelé" marcou um golo espetacular no apronto de ontem frente à equipa B. Veja o resumo!',
    entityName: 'Academia Sambizanga',
    entityType: 'club',
    entityLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=100&auto=format&fit=crop&q=80',
    timestamp: 'Há 2 horas',
    mediaUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80',
    actionUrl: '/matches',
    likesCount: 142,
    hasLiked: false,
  },
  {
    id: 'feed-02',
    type: 'match_result',
    title: 'Vitória expressiva nos Juniores Sub-17 (4 - 1)',
    summary: 'O Petro de Luanda venceu no fim de semana passado e garantiu a liderança isolada do Campeonato Provincial.',
    entityName: 'Petro Atlético de Luanda',
    entityType: 'club',
    entityLogo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=100&auto=format&fit=crop&q=80',
    timestamp: 'Ontem às 18:40',
    likesCount: 89,
    hasLiked: true,
  },
  {
    id: 'feed-03',
    type: 'award',
    title: 'Zito Luvumbo eleito Jogador do Mês de Setembro',
    summary: 'Com 5 golos e 3 assistências em 4 jogos, o atleta foi votado pelos adeptos como a figura de destaque.',
    entityName: 'Girabola 2026/27',
    entityType: 'competition',
    timestamp: 'Há 2 dias',
    mediaUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
    likesCount: 310,
    hasLiked: true,
  },
]

export const MOCK_LEADERBOARD: FanLeaderboardUser[] = [
  {
    id: 'u-1',
    name: 'Manuel "Tricolor" Neto',
    favoriteClub: 'Petro de Luanda',
    points: 480,
    correctPredictions: 18,
    rank: 1,
  },
  {
    id: 'u-2',
    name: 'Domingos Chivela',
    favoriteClub: '1º de Agosto',
    points: 445,
    correctPredictions: 16,
    rank: 2,
  },
  {
    id: 'u-3',
    name: 'Cláudio Kassoma',
    favoriteClub: 'Sagrada Esperança',
    points: 410,
    correctPredictions: 14,
    rank: 3,
  },
  {
    id: 'u-current',
    name: 'Você (Adepto Oficial)',
    favoriteClub: 'Petro de Luanda',
    points: 290,
    correctPredictions: 11,
    rank: 14,
    isCurrentUser: true,
  },
]

export const MOCK_FAN_STATS: FanStats = {
  followedClubsCount: 2,
  followedPlayersCount: 2,
  totalPredictions: 15,
  correctPredictions: 11,
  points: 290,
  rank: 14,
}
