import { ROUTES } from '@/constants'

export const onboardingRoutes = {
  root: ROUTES.ONBOARDING,
  branding: ROUTES.ONBOARDING_BRANDING,
  competition: ROUTES.ONBOARDING_COMPETITION,
  review: ROUTES.ONBOARDING_REVIEW,
  player: ROUTES.ONBOARDING_PLAYER,
  playerWelcome: ROUTES.ONBOARDING_PLAYER_WELCOME,
  playerFootball: ROUTES.ONBOARDING_PLAYER_FOOTBALL,
  playerProfile: ROUTES.ONBOARDING_PLAYER_PROFILE,
  playerIdentity: ROUTES.ONBOARDING_PLAYER_IDENTITY,
  playerContact: ROUTES.ONBOARDING_PLAYER_CONTACT,
  playerGuardian: ROUTES.ONBOARDING_PLAYER_GUARDIAN,
  playerClub: ROUTES.ONBOARDING_PLAYER_CLUB,
  playerReview: ROUTES.ONBOARDING_PLAYER_REVIEW,
  playerComplete: ROUTES.ONBOARDING_PLAYER_COMPLETE,
}
