import { ROUTES } from '@/constants'

export const onboardingRoutes = {
  root: ROUTES.ONBOARDING,
  branding: ROUTES.ONBOARDING_BRANDING,
  competition: ROUTES.ONBOARDING_COMPETITION,
  review: ROUTES.ONBOARDING_REVIEW,
  player: ROUTES.ONBOARDING_PLAYER,
  playerFootball: ROUTES.ONBOARDING_PLAYER_FOOTBALL,
  playerProfile: ROUTES.ONBOARDING_PLAYER_PROFILE,
  playerReview: ROUTES.ONBOARDING_PLAYER_REVIEW,
}
