export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  ORGANIZATIONS: '/organizations',
  ORGANIZATION_DETAIL: (slug: string) => `/organizations/${slug}`,
  ONBOARDING: '/onboarding',
  ONBOARDING_BRANDING: '/onboarding/branding',
  ONBOARDING_COMPETITION: '/onboarding/competition',
  ONBOARDING_REVIEW: '/onboarding/review',
  REGISTER_ORGANIZATION: '/register/organization',
  ORGANIZATION_SETTINGS: '/organization/settings',
  DASHBOARD_ORGANIZATION: '/dashboard/organization',
  DASHBOARD_ORGANIZATION_MEMBERS: '/dashboard/organization/members',
  DASHBOARD_ORGANIZATION_AFFILIATIONS: '/dashboard/organization/affiliations',
  DASHBOARD_CLUB: '/dashboard/club',
  DASHBOARD_CLUB_SETTINGS: '/dashboard/club/settings',
  DASHBOARD_CLUB_MEMBERS: '/dashboard/club/members',
  DASHBOARD_CLUB_DOCUMENTS: '/dashboard/club/documents',
  DASHBOARD_CLUB_SPONSORS: '/dashboard/club/sponsors',
  DASHBOARD_CLUB_TRANSFERS: '/dashboard/club/transfers',
  DASHBOARD_CLUB_TRANSFERS_CREATE: '/dashboard/club/transfers/create',
  DASHBOARD_COMPETITION: '/dashboard/competition',
  DASHBOARD_COMPETITIONS_CREATE: '/dashboard/competitions/create',
  DASHBOARD_COMPETITIONS_SETTINGS: (id: string) => `/dashboard/competitions/${id}/settings`,
  DASHBOARD_COMPETITIONS_REGISTRATION: (id: string) => `/dashboard/competitions/${id}/registration`,
  DASHBOARD_COMPETITIONS_SCHEDULE: (id: string) => `/dashboard/competitions/${id}/schedule`,
  CLUBS: '/clubs',
  PLAYERS: '/players',
  PLAYER_DETAIL: (slug: string) => `/players/${slug}`,
  PLAYER_CREATE: '/players/create',
  PLAYER_EDIT: (slug: string) => `/players/${slug}/edit`,
  DASHBOARD_PLAYER: '/dashboard/player',
  DASHBOARD_PLAYER_SETTINGS: '/dashboard/player/settings',
  DASHBOARD_CLUB_REGISTER_PLAYER: '/dashboard/club/register-player',
  FANS: '/fans',
  // Competition public routes
  COMPETITIONS: '/competitions',
  COMPETITION_DETAIL: (id: string) => `/competitions/${id}`,
  COMPETITION_RANKINGS: (id: string) => `/competitions/${id}/rankings`,
  COMPETITION_SUSPENSIONS: (id: string) => `/competitions/${id}/suspensions`,
  // Competition admin (dashboard) routes
  COMPETITION_CREATE: '/dashboard/competitions/create',
  COMPETITION_SETTINGS: (id: string) => `/dashboard/competitions/${id}/settings`,
  COMPETITION_REGISTRATION: (id: string) => `/dashboard/competitions/${id}/registration`,
  COMPETITION_SCHEDULE: (id: string) => `/dashboard/competitions/${id}/schedule`,
  // Match center
  MATCH_CENTER: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}`,
  MATCH_LINEUP: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}/lineup`,
  MATCH_REPORT: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}/report`,
  // Other modules
  MATCHES: '/matches',
  RANKINGS: '/rankings',
  NEWS: '/news',
  STADIUMS: '/stadiums',
  TRANSFERS: '/transfers',
  SUBSCRIPTIONS: '/subscriptions',
  NOTIFICATIONS: '/notifications',
  NOT_FOUND_PAGE: '/404',
  NOT_FOUND: '*',
}


export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REGISTER: '/auth/register',
    REGISTER_ORGANIZATION: '/auth/register/organization/',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  USERS: {
    LIST: '/users',
    GET: (id: string) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
  },
  ORGANIZATIONS: {
    ME: '/organizations/me/',
    LOGO: '/organizations/me/logo/',
    BANNER: '/organizations/me/banner/',
    LAUNCH: '/organizations/me/launch/',
    ONBOARDING_STATUS: '/organizations/me/onboarding-status/',
    MEMBERS: '/organizations/me/members/',
    MEMBER_DETAIL: (id: string) => `/organizations/me/members/${id}/`,
    CLUB_REQUESTS: '/organizations/me/club-requests/',
    CLUB_REQUEST_REVIEW: (id: string) => `/organizations/me/club-requests/${id}/`,
    PUBLIC: {
      LIST: '/organizations/public/',
      GET: (slug: string) => `/organizations/public/${slug}/`,
      KPIS: (slug: string) => `/organizations/public/${slug}/kpis/`,
      HISTORY: (slug: string) => `/organizations/public/${slug}/history/`,
      TOURNAMENTS: (slug: string) => `/organizations/public/${slug}/tournaments/`,
      CLUBS: (slug: string) => `/organizations/public/${slug}/clubs/`,
      SUBSCRIBE: (slug: string) => `/organizations/public/${slug}/subscribe/`,
      UNSUBSCRIBE: (slug: string) => `/organizations/public/${slug}/unsubscribe/`,
    },
  },
  CLUBS: {
    LIST: '/clubs/',
    ME: '/clubs/me/',
    LOGO: '/clubs/me/logo/',
    CREATE: '/clubs/',
    ACTIVATE: (slug: string) => `/clubs/${slug}/activate/`,
    SUSPEND: (slug: string) => `/clubs/${slug}/suspend/`,
    MEMBERS: (slug: string) => `/clubs/${slug}/members/`,
    MEMBER_DETAIL: (slug: string, memberId: string) => `/clubs/${slug}/members/${memberId}/`,
    DOCUMENTS: (slug: string) => `/clubs/${slug}/documents/`,
    DOCUMENT_DETAIL: (slug: string, documentId: string) => `/clubs/${slug}/documents/${documentId}/`,
    SPONSORS: (slug: string) => `/clubs/${slug}/sponsors/`,
    SPONSOR_DETAIL: (slug: string, sponsorId: string) => `/clubs/${slug}/sponsors/${sponsorId}/`,
    TRANSFERS: '/clubs/transfers/',
    TRANSFER_DETAIL: (transferId: string) => `/clubs/transfers/${transferId}/`,
    TRANSFER_APPROVE: (transferId: string) => `/clubs/transfers/${transferId}/approve/`,
    TRANSFER_REJECT: (transferId: string) => `/clubs/transfers/${transferId}/reject/`,
    PUBLIC: {
      LIST: '/clubs/public/',
      GET: (slug: string) => `/clubs/public/${slug}/`,
      KPIS: (slug: string) => `/clubs/public/${slug}/kpis/`,
      SQUAD: (slug: string) => `/clubs/public/${slug}/squad/`,
      STAFF: (slug: string) => `/clubs/public/${slug}/staff/`,
      DOCUMENTS: (slug: string) => `/clubs/public/${slug}/documents/`,
      SPONSORS: (slug: string) => `/clubs/public/${slug}/sponsors/`,
    },
  },
  PLAYERS: {
    LIST: '/players/',
    SEARCH: '/players/search/',
    ME: '/players/me/',
    ME_AVATAR: '/players/me/avatar/',
    GET: (slug: string) => `/players/${slug}/`,
    CREATE: '/players/',
    UPDATE: (slug: string) => `/players/${slug}/`,
    AVATAR: (slug: string) => `/players/${slug}/avatar/`,
    REGISTER: (slug: string) => `/players/${slug}/register/`,
    // Documents
    DOCUMENTS: (slug: string) => `/players/${slug}/documents/`,
    DOCUMENT_DETAIL: (slug: string, documentId: string) => `/players/${slug}/documents/${documentId}/`,
    DOCUMENT_VERIFY: (slug: string, documentId: string) => `/players/${slug}/documents/${documentId}/verify/`,
    // Videos
    VIDEOS: (slug: string) => `/players/${slug}/videos/`,
    VIDEO_DETAIL: (slug: string, videoId: string) => `/players/${slug}/videos/${videoId}/`,
    VIDEO_PUBLISH: (slug: string, videoId: string) => `/players/${slug}/videos/${videoId}/publish/`,
    // Achievements
    ACHIEVEMENTS: (slug: string) => `/players/${slug}/achievements/`,
    ACHIEVEMENT_DETAIL: (slug: string, achievementId: string) => `/players/${slug}/achievements/${achievementId}/`,
    ACHIEVEMENT_VERIFY: (slug: string, achievementId: string) => `/players/${slug}/achievements/${achievementId}/verify/`,
  },
  COMPETITIONS: {
    LIST: '/competitions/',
    GET: (id: string) => `/competitions/${id}/`,
    CREATE: '/competitions/',
    UPDATE: (id: string) => `/competitions/${id}/`,
    DELETE: (id: string) => `/competitions/${id}/`,
    REGISTER_CLUB: (id: string) => `/competitions/${id}/register-club/`,
    GENERATE_SCHEDULE: (id: string) => `/competitions/${id}/generate-schedule/`,
    MATCHES: (id: string) => `/competitions/${id}/matches/`,
    STANDINGS: (id: string) => `/competitions/${id}/standings/`,
    UPDATE_MATCH: (matchId: string) => `/competitions/matches/${matchId}/`,
    MATCH_EVENTS: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}/events/`,
    DELETE_EVENT: (compId: string, matchId: string, eventId: string) => `/competitions/${compId}/matches/${matchId}/events/${eventId}/`,
    PLAYER_STATS: (compId: string) => `/competitions/${compId}/stats/`,
  },
  MATCHES: {
    LIST: '/matches',
    GET: (id: string) => `/matches/${id}`,
    CREATE: '/matches',
    UPDATE: (id: string) => `/matches/${id}`,
    DELETE: (id: string) => `/matches/${id}`,
  },
  TRANSFERS: {
    LIST: '/transfers',
    GET: (id: string) => `/transfers/${id}`,
    CREATE: '/transfers',
    UPDATE: (id: string) => `/transfers/${id}`,
    DELETE: (id: string) => `/transfers/${id}`,
  },
  NEWS: {
    LIST: '/news',
    GET: (id: string) => `/news/${id}`,
    CREATE: '/news',
    UPDATE: (id: string) => `/news/${id}`,
    DELETE: (id: string) => `/news/${id}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    UNREAD_COUNT: '/notifications/unread-count/',
    MARK_READ: (id: string) => `/notifications/${id}/mark-read/`,
  },
}
