export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  ORGANIZATIONS: '/organizations',
  ONBOARDING: '/onboarding',
  REGISTER_ORGANIZATION: '/register/organization',
  ORGANIZATION_SETTINGS: '/organization/settings',
  DASHBOARD_ORGANIZATION: '/dashboard/organization',
  CLUBS: '/clubs',
  PLAYERS: '/players',
  FANS: '/fans',
  COMPETITIONS: '/competitions',
  MATCHES: '/matches',
  RANKINGS: '/rankings',
  NEWS: '/news',
  STADIUMS: '/stadiums',
  TRANSFERS: '/transfers',
  SUBSCRIPTIONS: '/subscriptions',
  NOTIFICATIONS: '/notifications',
  NOT_FOUND: '*',
}

export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REGISTER: '/auth/register',
    REGISTER_ORGANIZATION: '/auth/register/organization/',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  USERS: {
    LIST: '/users',
    GET: (id: string) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
  },
  ORGANIZATIONS: {
    ME: '/organizations/me/',
    LOGO: '/organizations/me/logo/',
    LAUNCH: '/organizations/me/launch/',
    ONBOARDING_STATUS: '/organizations/me/onboarding-status/',
    PUBLIC: {
      LIST: '/organizations/public/',
      GET: (slug: string) => `/organizations/public/${slug}/`,
      KPIS: (slug: string) => `/organizations/public/${slug}/kpis/`,
      HISTORY: (slug: string) => `/organizations/public/${slug}/history/`,
      TOURNAMENTS: (slug: string) => `/organizations/public/${slug}/tournaments/`,
      CLUBS: (slug: string) => `/organizations/public/${slug}/clubs/`,
      SUBSCRIBE: (slug: string) => `/organizations/public/${slug}/subscribe/`,
      UNSUBSCRIBE: (slug: string) => `/organizations/public/${slug}/unsubscribe/`,
    },
  },
  CLUBS: {
    LIST: '/clubs',
    PUBLIC: {
      LIST: '/clubs/public',
      GET: (slug: string) => `/clubs/public/${slug}`,
    },
    GET: (id: string) => `/clubs/${id}`,
    CREATE: '/clubs',
    UPDATE: (id: string) => `/clubs/${id}`,
    DELETE: (id: string) => `/clubs/${id}`,
  },
  PLAYERS: {
    LIST: '/players',
    GET: (id: string) => `/players/${id}`,
    CREATE: '/players',
    UPDATE: (id: string) => `/players/${id}`,
    DELETE: (id: string) => `/players/${id}`,
  },
  COMPETITIONS: {
    LIST: '/competitions',
    GET: (id: string) => `/competitions/${id}`,
    CREATE: '/competitions',
    UPDATE: (id: string) => `/competitions/${id}`,
    DELETE: (id: string) => `/competitions/${id}`,
  },
  MATCHES: {
    LIST: '/matches',
    GET: (id: string) => `/matches/${id}`,
    CREATE: '/matches',
    UPDATE: (id: string) => `/matches/${id}`,
    DELETE: (id: string) => `/matches/${id}`,
  },
  TRANSFERS: {
    LIST: '/transfers',
    GET: (id: string) => `/transfers/${id}`,
    CREATE: '/transfers',
    UPDATE: (id: string) => `/transfers/${id}`,
    DELETE: (id: string) => `/transfers/${id}`,
  },
  NEWS: {
    LIST: '/news',
    GET: (id: string) => `/news/${id}`,
    CREATE: '/news',
    UPDATE: (id: string) => `/news/${id}`,
    DELETE: (id: string) => `/news/${id}`,
  },
}
