export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  ORGANIZATIONS: '/organizations',
  ORGANIZATION_DETAIL: (slug: string) => `/organizations/${slug}`,
  ONBOARDING: '/onboarding',
  ONBOARDING_BRANDING: '/onboarding/branding',
  ONBOARDING_COMPETITION: '/onboarding/competition',
  ONBOARDING_REVIEW: '/onboarding/review',
  ONBOARDING_PLAYER: '/onboarding/player',
  ONBOARDING_PLAYER_WELCOME: '/onboarding/player/welcome',
  ONBOARDING_PLAYER_FOOTBALL: '/onboarding/player/football',
  ONBOARDING_PLAYER_PROFILE: '/onboarding/player/profile',
  ONBOARDING_PLAYER_REVIEW: '/onboarding/player/review',
  ONBOARDING_PLAYER_COMPLETE: '/onboarding/player/complete',
  ONBOARDING_PLAYER_IDENTITY: '/onboarding/player/identity',
  ONBOARDING_PLAYER_CONTACT: '/onboarding/player/contact',
  ONBOARDING_PLAYER_GUARDIAN: '/onboarding/player/guardian',
  ONBOARDING_PLAYER_DOCUMENTS: '/onboarding/player/documents',
  ONBOARDING_PLAYER_CLUB: '/onboarding/player/club',
  REGISTER_PLAYER: '/register/player',
  REGISTER_CLUB: '/register/club',
  REGISTER_FAN: '/register/fan',
  REGISTER_ORGANIZATION: '/register/organization',
  CLUB_ONBOARDING: '/club/onboarding',
  ORGANIZATION_SETTINGS: '/organization/settings',
  DASHBOARD_ORGANIZATION: '/dashboard/organization',
  DASHBOARD_ORGANIZATION_CLUBS: '/dashboard/organization/clubs',
  DASHBOARD_ORGANIZATION_PLAYERS: '/dashboard/organization/players',
  DASHBOARD_ORGANIZATION_COMPETITIONS: '/dashboard/organization/competitions',
  DASHBOARD_ORGANIZATION_MEMBERS: '/dashboard/organization/members',
  DASHBOARD_ORGANIZATION_AFFILIATIONS: '/dashboard/organization/affiliations',
  DASHBOARD_ORGANIZATION_LINEUPS: '/dashboard/organization/lineups',
  DASHBOARD_CLUB: '/dashboard/club',
  DASHBOARD_CLUB_SETTINGS: '/dashboard/club/settings',
  DASHBOARD_CLUB_MEMBERS: '/dashboard/club/members',
  DASHBOARD_CLUB_DOCUMENTS: '/dashboard/club/documents',
  DASHBOARD_CLUB_SPONSORS: '/dashboard/club/sponsors',
  DASHBOARD_CLUB_TRANSFERS: '/dashboard/club/transfers',
  DASHBOARD_CLUB_TRANSFERS_CREATE: '/dashboard/club/transfers/create',
  DASHBOARD_CLUB_TRANSFER_DETAIL: (id: string) => `/dashboard/club/transfers/${id}`,
  DASHBOARD_TRANSFERS: '/dashboard/transfers',
  DASHBOARD_TRANSFER_DETAIL: (id: string) => `/dashboard/transfers/${id}`,
  DASHBOARD_TRANSFERS_CREATE: '/dashboard/transfers/create',
  DASHBOARD_COMPETITION: '/dashboard/competition',
  DASHBOARD_COMPETITIONS_LIST: '/dashboard/competitions',
  DASHBOARD_COMPETITIONS_MATCHES: '/dashboard/competitions/matches',
  DASHBOARD_COMPETITIONS_CREATE: '/dashboard/competitions/create',
  DASHBOARD_COMPETITIONS_SETTINGS: (id: string) => `/dashboard/competitions/${id}/settings`,
  DASHBOARD_COMPETITIONS_REGISTRATION: (id: string) => `/dashboard/competitions/${id}/registration`,
  DASHBOARD_COMPETITIONS_SCHEDULE: (id: string) => `/dashboard/competitions/${id}/schedule`,
  CLUBS: '/clubs',
  PLAYERS: '/players',
  PLAYER_DETAIL: (slug: string) => `/players/${slug}`,
  PLAYER_CREATE: '/players/create',
  DASHBOARD_PLAYERS_CREATE: '/dashboard/players/create',
  PLAYER_EDIT: (slug: string) => `/players/${slug}/edit`,
  DASHBOARD_PLAYER: '/dashboard/player',
  DASHBOARD_PLAYER_SETTINGS: '/dashboard/player/settings',
  DASHBOARD_PLAYER_LINK_CLUB: '/dashboard/player/link-club',
  DASHBOARD_CLUB_REGISTER_PLAYER: '/dashboard/club/register-player',
  DASHBOARD_CLUB_PLAYER_REQUESTS: '/dashboard/club/player-requests',
  DASHBOARD_CLUB_SQUAD: '/dashboard/club/squad',
  DASHBOARD_CLUB_COMPETITIONS: '/dashboard/club/competitions',
  DASHBOARD_CLUB_MATCH_LINEUP: (matchId: string) => `/dashboard/club/matches/${matchId}/lineup`,
  FANS: '/fans',
  // Competition public routes
  COMPETITIONS: '/competitions',
  COMPETITION_DETAIL: (id: string) => `/competitions/${id}`,
  COMPETITION_RANKINGS: (id: string) => `/competitions/${id}/rankings`,
  COMPETITION_SUSPENSIONS: (id: string) => `/competitions/${id}/suspensions`,
  // Competition admin (dashboard) routes
  COMPETITION_CREATE: '/dashboard/competitions/create',
  COMPETITION_ADMIN_DASHBOARD: (id: string) => `/dashboard/competitions/${id}`,
  COMPETITION_SETTINGS: (id: string) => `/dashboard/competitions/${id}/settings`,
  COMPETITION_REGISTRATION: (id: string) => `/dashboard/competitions/${id}/registration`,
  COMPETITION_DRAW: (id: string) => `/dashboard/competitions/${id}/draw`,
  COMPETITION_ADMIN_RANKINGS: (id: string) => `/dashboard/competitions/${id}/rankings`,
  COMPETITION_ADMIN_SUSPENSIONS: (id: string) => `/dashboard/competitions/${id}/suspensions`,
  COMPETITION_ADMIN_REGULATIONS: (id: string) => `/dashboard/competitions/${id}/regulations`,
  // Match center
  MATCH_CENTER: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}`,
  MATCH_LINEUP: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}/lineup`,
  MATCH_REPORT: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}/report`,
  // Dashboard match center
  DASHBOARD_MATCH_CENTER: (compId: string, matchId: string) => `/dashboard/competitions/${compId}/matches/${matchId}`,
  DASHBOARD_MATCH_LINEUP: (compId: string, matchId: string) => `/dashboard/competitions/${compId}/matches/${matchId}/lineup`,
  DASHBOARD_MATCH_REPORT: (compId: string, matchId: string) => `/dashboard/competitions/${compId}/matches/${matchId}/report`,
  // Other modules
  MATCHES: '/matches',
  RANKINGS: '/rankings',
  NEWS: '/news',
  STADIUMS: '/stadiums',
  TRANSFERS: '/transfers',
  SUBSCRIPTIONS: '/subscriptions',
  NOTIFICATIONS: '/notifications',
  NOT_FOUND_PAGE: '/404',
  NOT_FOUND: '*',
}

export const API_ROUTES = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REGISTER: '/auth/register',
    REGISTER_ORGANIZATION: '/auth/register/organization/',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
  },
  USERS: {
    LIST: '/users',
    GET: (id: string) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
  },
  ORGANIZATIONS: {
    ME: '/organizations/me/',
    LOGO: '/organizations/me/logo/',
    BANNER: '/organizations/me/banner/',
    LAUNCH: '/organizations/me/launch/',
    ONBOARDING_STATUS: '/organizations/me/onboarding-status/',
    MEMBERS: '/organizations/me/members/',
    MEMBER_DETAIL: (id: string) => `/organizations/me/members/${id}/`,
    CLUB_REQUESTS: '/organizations/me/club-requests/',
    CLUB_REQUEST_REVIEW: (id: string) => `/organizations/me/club-requests/${id}/`,
    PENDING_LINEUPS: '/organizations/me/lineups/pending/',
    PENDING_LINEUP_REVIEW: (id: string) => `/organizations/me/lineups/pending/${id}/review/`,
    PUBLIC: {
      LIST: '/organizations/public/',
      GET: (slug: string) => `/organizations/public/${slug}/`,
      KPIS: (slug: string) => `/organizations/public/${slug}/kpis/`,
      HISTORY: (slug: string) => `/organizations/public/${slug}/history/`,
      TOURNAMENTS: (slug: string) => `/organizations/public/${slug}/tournaments/`,
      CLUBS: (slug: string) => `/organizations/public/${slug}/clubs/`,
      PLAYERS: (slug: string) => `/organizations/public/${slug}/players/`,
      CLUB_REQUESTS: (slug: string) => `/organizations/public/${slug}/club-requests/`,
      SUBSCRIBE: (slug: string) => `/organizations/public/${slug}/subscribe/`,
      UNSUBSCRIBE: (slug: string) => `/organizations/public/${slug}/unsubscribe/`,
    },
  },
  CLUBS: {
    LIST: '/clubs/',
    ME: '/clubs/me/',
    ME_COMPETITIONS: '/clubs/me/competitions/',
    ME_MATCHES: '/clubs/me/matches/',
    ME_STANDINGS: '/clubs/me/standings/',
    LOGO: '/clubs/me/logo/',
    PLAYER_REGISTRATION_REQUESTS: '/clubs/me/player-registration-requests/',
    PLAYER_REGISTRATION_REQUEST_REVIEW: (requestId: string) =>
      `/clubs/me/player-registration-requests/${requestId}/`,
    CREATE: '/clubs/',
    ACTIVATE: (slug: string) => `/clubs/${slug}/activate/`,
    SUSPEND: (slug: string) => `/clubs/${slug}/suspend/`,
    MEMBERS: (slug: string) => `/clubs/${slug}/members/`,
    MEMBER_DETAIL: (slug: string, memberId: string) => `/clubs/${slug}/members/${memberId}/`,
    DOCUMENTS: (slug: string) => `/clubs/${slug}/documents/`,
    DOCUMENT_DETAIL: (slug: string, documentId: string) => `/clubs/${slug}/documents/${documentId}/`,
    SPONSORS: (slug: string) => `/clubs/${slug}/sponsors/`,
    SPONSOR_DETAIL: (slug: string, sponsorId: string) => `/clubs/${slug}/sponsors/${sponsorId}/`,
    TRANSFERS: '/clubs/transfers/',
    TRANSFER_DETAIL: (transferId: string) => `/clubs/transfers/${transferId}/`,
    TRANSFER_APPROVE: (transferId: string) => `/clubs/transfers/${transferId}/approve/`,
    TRANSFER_REJECT: (transferId: string) => `/clubs/transfers/${transferId}/reject/`,
    TRANSFER_COMPLETE: (transferId: string) => `/clubs/transfers/${transferId}/complete/`,
    TRANSFER_CANCEL: (transferId: string) => `/clubs/transfers/${transferId}/cancel/`,
    TRANSFER_EXTEND_LOAN: (transferId: string) => `/clubs/transfers/${transferId}/extend_loan/`,
    TRANSFER_RETURN_LOAN: (transferId: string) => `/clubs/transfers/${transferId}/return_loan/`,
    TRANSFER_MAKE_PERMANENT: (transferId: string) => `/clubs/transfers/${transferId}/make_permanent/`,
    TRANSFER_PENDING_APPROVALS: '/clubs/transfers/pending_approvals/',
    TRANSFER_ACTIVE_LOANS: '/clubs/transfers/active_loans/',
    TRANSFER_EXPIRING_LOANS: '/clubs/transfers/expiring_loans/',
    PUBLIC: {
      LIST: '/clubs/public/',
      GET: (slug: string) => `/clubs/public/${slug}/`,
      KPIS: (slug: string) => `/clubs/public/${slug}/kpis/`,
      SQUAD: (slug: string) => `/clubs/public/${slug}/squad/`,
      STAFF: (slug: string) => `/clubs/public/${slug}/staff/`,
      DOCUMENTS: (slug: string) => `/clubs/public/${slug}/documents/`,
      SPONSORS: (slug: string) => `/clubs/public/${slug}/sponsors/`,
      COMPETITIONS: (slug: string) => `/clubs/public/${slug}/competitions/`,
      MATCHES: (slug: string) => `/clubs/public/${slug}/matches/`,
      STANDINGS: (slug: string) => `/clubs/public/${slug}/standings/`,
    },
  },
  PLAYERS: {
    LIST: '/players/',
    SEARCH: '/players/search/',
    ME: '/players/me/',
    ME_ONBOARDING_STATUS: '/players/me/onboarding-status/',
    ME_AVATAR: '/players/me/avatar/',
    ME_REGISTRATION_REQUESTS: '/players/me/registration-requests/',
    GET: (slug: string) => `/players/${slug}/`,
    CREATE: '/players/',
    UPDATE: (slug: string) => `/players/${slug}/`,
    AVATAR: (slug: string) => `/players/${slug}/avatar/`,
    REGISTER: (slug: string) => `/players/${slug}/register/`,
    // Documents
    DOCUMENTS: (slug: string) => `/players/${slug}/documents/`,
    DOCUMENT_DETAIL: (slug: string, documentId: string) => `/players/${slug}/documents/${documentId}/`,
    DOCUMENT_VERIFY: (slug: string, documentId: string) => `/players/${slug}/documents/${documentId}/verify/`,
    // Videos
    VIDEOS: (slug: string) => `/players/${slug}/videos/`,
    VIDEO_DETAIL: (slug: string, videoId: string) => `/players/${slug}/videos/${videoId}/`,
    VIDEO_PUBLISH: (slug: string, videoId: string) => `/players/${slug}/videos/${videoId}/publish/`,
    // Achievements
    ACHIEVEMENTS: (slug: string) => `/players/${slug}/achievements/`,
    ACHIEVEMENT_DETAIL: (slug: string, achievementId: string) => `/players/${slug}/achievements/${achievementId}/`,
    ACHIEVEMENT_VERIFY: (slug: string, achievementId: string) => `/players/${slug}/achievements/${achievementId}/verify/`,
    // Career & Statistics (slug-based, Phase 1/2)
    CAREER: (slug: string) => `/players/${slug}/career/`,
    STATISTICS: (slug: string) => `/players/${slug}/statistics/`,
    STATISTICS_SEASON: (slug: string, season: string) => `/players/${slug}/statistics/${season}/`,
    FOOTBALL_PROFILE: (slug: string) => `/players/${slug}/football-profile/`,
    // Contact & Identity (slug-based, Phase 1)
    CONTACT: (slug: string) => `/players/${slug}/contact/`,
    EMERGENCY_CONTACTS: (slug: string) => `/players/${slug}/emergency-contacts/`,
    IDENTITY_DOCUMENTS: (slug: string) => `/players/${slug}/identity-documents/`,
    IDENTITY_DOCUMENT_DETAIL: (slug: string, docId: string) => `/players/${slug}/identity-documents/${docId}/`,
    IDENTITY_DOCUMENT_VERIFY: (slug: string, docId: string) => `/players/${slug}/identity-documents/${docId}/verify/`,
    // Invite
    INVITE: '/players/invite/',
    INVITE_REDEEM: '/players/invite/redeem/',
    // Onboarding step
    ME_ONBOARDING_COMPLETE_STEP: '/players/me/onboarding/complete-step/',
    // Phase 3 — UUID-based (contracts, agents, training)
    CONTRACTS: (playerId: string) => `/players/${playerId}/contracts/`,
    CONTRACT_DETAIL: (playerId: string, id: string) => `/players/${playerId}/contracts/${id}/`,
    CONTRACT_SIGN: (playerId: string, id: string) => `/players/${playerId}/contracts/${id}/sign/`,
    CONTRACT_RENEW: (playerId: string, id: string) => `/players/${playerId}/contracts/${id}/renew/`,
    CONTRACT_TERMINATE: (playerId: string, id: string) => `/players/${playerId}/contracts/${id}/terminate/`,
    AGENTS: (playerId: string) => `/players/${playerId}/agents/`,
    AGENT_DETAIL: (playerId: string, relId: string) => `/players/${playerId}/agents/${relId}/`,
    AGENTS_LIST: '/players/agents/',
    AGENT_ENTITY_DETAIL: (agentId: string) => `/players/agents/${agentId}/`,
    TRAINING_HISTORY: (playerId: string) => `/players/${playerId}/training-history/`,
    TRAINING_HISTORY_DETAIL: (playerId: string, id: string) => `/players/${playerId}/training-history/${id}/`,
    TRAINING_HISTORY_VERIFY: (playerId: string, id: string) => `/players/${playerId}/training-history/${id}/verify/`,
    TRAINING_COMPENSATION: (playerId: string) => `/players/${playerId}/training-compensation/`,
    // Phase 4 — UUID-based (medical)
    MEDICAL: (playerId: string) => `/players/${playerId}/medical/`,
    MEDICAL_HISTORY: (playerId: string) => `/players/${playerId}/medical/history/`,
    MEDICAL_DOCUMENTS: (playerId: string) => `/players/${playerId}/medical/documents/`,
    MEDICAL_DOCUMENT_DETAIL: (playerId: string, docId: string) => `/players/${playerId}/medical/documents/${docId}/`,
    MEDICAL_DOCUMENT_VERIFY: (playerId: string, docId: string) => `/players/${playerId}/medical/documents/${docId}/verify/`,
    MEDICAL_DOCUMENT_REJECT: (playerId: string, docId: string) => `/players/${playerId}/medical/documents/${docId}/reject/`,
    // NOTE: national-team-call-ups endpoint não existe no backend ainda — desactivado
    // NATIONAL_TEAM_CALLUPS: (playerId: string) => `/players/${playerId}/national-team-call-ups/`,
  },
  COMPETITIONS: {
    LIST: '/competitions/',
    GET: (id: string) => `/competitions/${id}/`,
    CREATE: '/competitions/',
    UPDATE: (id: string) => `/competitions/${id}/`,
    DELETE: (id: string) => `/competitions/${id}/`,
    REGISTER_CLUB: (id: string) => `/competitions/${id}/register-club/`,
    GENERATE_SCHEDULE: (id: string) => `/competitions/${id}/generate-schedule/`,
    DRAW: (id: string) => `/competitions/${id}/draw/`,
    MATCHES: (id: string) => `/competitions/${id}/matches/`,
    CREATE_MATCH: (id: string) => `/competitions/${id}/matches/`,
    STANDINGS: (id: string) => `/competitions/${id}/standings/`,
    BRACKET: (id: string) => `/competitions/${id}/bracket/`,
    ROUNDS: (id: string) => `/competitions/${id}/rounds/`,
    UPDATE_MATCH: (matchId: string) => `/competitions/matches/${matchId}/`,
    MATCH_EVENTS: (compId: string, matchId: string) => `/competitions/${compId}/matches/${matchId}/events/`,
    DELETE_EVENT: (compId: string, matchId: string, eventId: string) => `/competitions/${compId}/matches/${matchId}/events/${eventId}/`,
    PLAYER_STATS: (compId: string) => `/competitions/${compId}/stats/`,
  },
  MATCHES: {
    LIST: '/matches',
    GET: (id: string) => `/matches/${id}`,
    CREATE: '/matches',
    UPDATE: (id: string) => `/matches/${id}`,
    DELETE: (id: string) => `/matches/${id}`,
  },
  TRANSFERS: {
    LIST: '/clubs/transfers/',
    GET: (id: string) => `/clubs/transfers/${id}/`,
    CREATE: '/clubs/transfers/',
    APPROVE: (id: string) => `/clubs/transfers/${id}/approve/`,
    REJECT: (id: string) => `/clubs/transfers/${id}/reject/`,
    COMPLETE: (id: string) => `/clubs/transfers/${id}/complete/`,
    CANCEL: (id: string) => `/clubs/transfers/${id}/cancel/`,
    EXTEND_LOAN: (id: string) => `/clubs/transfers/${id}/extend_loan/`,
    RETURN_LOAN: (id: string) => `/clubs/transfers/${id}/return_loan/`,
    MAKE_PERMANENT: (id: string) => `/clubs/transfers/${id}/make_permanent/`,
    PENDING_APPROVALS: '/clubs/transfers/pending_approvals/',
    ACTIVE_LOANS: '/clubs/transfers/active_loans/',
    EXPIRING_LOANS: '/clubs/transfers/expiring_loans/',
  },
  NEWS: {
    LIST: '/news',
    GET: (id: string) => `/news/${id}`,
    CREATE: '/news',
    UPDATE: (id: string) => `/news/${id}`,
    DELETE: (id: string) => `/news/${id}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    UNREAD_COUNT: '/notifications/unread-count/',
    MARK_READ: (id: string) => `/notifications/${id}/mark-read/`,
    STREAM: '/notifications/stream/',
  },
}
