import { ROUTES } from '@/constants'

export const playerRoutes = {
  list: ROUTES.PLAYERS,
  comparison: ROUTES.PLAYER_COMPARISON,
  detail: (slug: string) => ROUTES.PLAYER_DETAIL(slug),
  create: ROUTES.PLAYER_CREATE,
  edit: (slug: string) => ROUTES.PLAYER_EDIT(slug),
  dashboard: ROUTES.DASHBOARD_PLAYER,
  career: ROUTES.DASHBOARD_PLAYER_CAREER,
  contracts: ROUTES.DASHBOARD_PLAYER_CONTRACTS,
  medical: ROUTES.DASHBOARD_PLAYER_MEDICAL,
  dashboardSettings: ROUTES.DASHBOARD_PLAYER_SETTINGS,
  media: ROUTES.DASHBOARD_PLAYER_MEDIA,
  linkClub: ROUTES.DASHBOARD_PLAYER_LINK_CLUB,
  clubRegister: ROUTES.DASHBOARD_CLUB_REGISTER_PLAYER,
  clubPlayerRequests: ROUTES.DASHBOARD_CLUB_PLAYER_REQUESTS,
}
