import { ROUTES } from '@/constants'

export const clubRoutes = {
  list: ROUTES.CLUBS,
  detail: (id: string) => `/clubs/${id}`,
  dashboard: ROUTES.DASHBOARD_CLUB,
  settings: ROUTES.DASHBOARD_CLUB_SETTINGS,
  members: ROUTES.DASHBOARD_CLUB_MEMBERS,
  documents: ROUTES.DASHBOARD_CLUB_DOCUMENTS,
  sponsors: ROUTES.DASHBOARD_CLUB_SPONSORS,
  transfers: ROUTES.DASHBOARD_CLUB_TRANSFERS,
  transferCreate: ROUTES.DASHBOARD_CLUB_TRANSFERS_CREATE,
  transferDetail: ROUTES.DASHBOARD_CLUB_TRANSFER_DETAIL,
  registerPlayer: ROUTES.DASHBOARD_CLUB_REGISTER_PLAYER,
  playerRequests: ROUTES.DASHBOARD_CLUB_PLAYER_REQUESTS,
  squad: ROUTES.DASHBOARD_CLUB_SQUAD,
  competitions: ROUTES.DASHBOARD_CLUB_COMPETITIONS,
}

